### ISSUE TITLE
use folding in coqbot minimize messages

### ISSUE THREAD

**Issue by gares** [coq/bot#171]
They are quite verbose. IMO `foo failed (howto minimize |>)` would be more effective.
For an example of folding in GH markdown, see https://github.com/LPCIC/elpi (the README has one).

**Comment by Zimmi48** [comment]
Related feedback by @palmskog here to not use full sentences and use emojis: https://coq.zulipchat.com/#narrow/stream/243318-coqbot-devs.20.26.20users/topic/coqbot.20comment.20messages

**Comment by JasonGross** [comment]
The Zulip feedback:

-----
I'm not at all a heavy user/reader of coqbot, but it always feels strange to me to use "plain English" sentences instead of some more artificial layout with color coding that is easier to break down quickly, for example:

:alert: CI failures at commit 2eb1bd1 without any failure in the test-suite

:check:  corresponding jobs for the base commit 95e359b succeeded. 

:question: ask me to try to extract a minimal test case from this so that it can be added to the test-suite.
- :tag: `@coqbot ci minimize` will minimize the following targets: `ci-aac_tactics`, `ci-cross_crypto`.

------

I'm not at all a heavy user/reader of coqbot, but it always feels strange to me to use "plain English" sentences instead of some more artificial layout with color coding that is easier to break down quickly, for example:

:alert: CI failures at commit 2eb1bd1 without any failure in the test-suite

:check:  corresponding jobs for the base commit 95e359b succeeded. 

:question: ask me to try to extract a minimal test case from this so that it can be added to the test-suite.
- :tag: `@coqbot ci minimize` will minimize the following targets: `ci-aac_tactics`, `ci-cross_crypto`.

------------

see also layout of pull request messages from the opam-publish tool: https://github.com/coq/opam-coq-archive/pull/1916#issue-1043703544

----------

**Comment by JasonGross** [comment]
We can also solicit feedback via reactions:
- 👍 for "this was useful"
- :-1: for "this was not useful"
- 👀 for "this helped me understand what's going on"
- 🚀 for "I plan to add this to the test-suite"
-

**Comment by Zimmi48** [comment]
Refined emoji-based comment:

------

:red_circle: CI failures at commit 2eb1bd1 without any failure in the test-suite

:heavy_check_mark: corresponding jobs for the base commit 95e359b succeeded. 

:grey_question: ask me to try to extract a minimal test case from this so that it can be added to the test-suite.

:runner: `@coqbot ci minimize` will minimize the following targets: `ci-aac_tactics`, `ci-cross_crypto`.

:warning: :hourglass: You may want to wait until the base pipeline finishes...

------

Alternative in case it was auto-run:

------

:red_circle: CI failures at commit 2eb1bd1 without any failure in the test-suite

:heavy_check_mark: corresponding jobs for the base commit 95e359b succeeded. 

:runner: I have automatically started minimization...

------

**Comment by JasonGross** [comment]
Notes:
- details summary needs `<code>`, not <code>`</code>
- we need to tell coqbot to avoid `<code>@coqbot`, not just <code>`@coqbot</code>
